version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_exclude:
          regex: WIP
      - do: label
        and:
          - must_exclude:
              regex: 'wip'
          - must_include:
              regex: 'junior'
              message: 'Add `junior` label for automerge'
      - do: approvals
        min:
          count: 1
        required:
          assignees: true
#    error:
#      - do: checks
#        status: 'failure'
#        payload:
#          title: 'Action/edits required'
#    fail:
#      - do: checks
#        status: 'failure'
#        payload:
#          title: 'Action/edits required'

  - when: issues.opened
    validate:
      - do: description
        no_empty:
          enabled: true
#    error:
#      - do: checks
#        status: 'action_required'
#        payload:
#          title: 'Action/edits required'
#    fail:
#      - do: checks
#        status: 'failure'
#        payload:
#          title: 'Action/edits required'
